name: Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '15'

      - name: Use MongoDB ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: '4.4'

      - name: Use Mosquitto ${{ matrix.mosquitto-version }}
        uses: namoshek/mosquitto-github-action@v0.1.0
        with:
          version: '1.6'

      - name: Install dependecies
        run: sudo DEBIAN_FRONTEND='noninteractive' apt install -y build-essential git sudo curl wget nano can-utils gnupg screen libmongoc-dev libbson-dev libmosquitto-dev

      - name: Install node dependencies
        run: npm install && cd test && npm install
      
      - name: Compile C
        run: npm run compile
      
      - name: Test moduled
        run: cd test && npm run test:moduled

      - name: Test partial
        run: cd test && npm run test:partial

      - name: Test general
        run: cd test && npm run test:general